### ISSUE TITLE
Add citystatezip Service Integration Tests

### ISSUE THREAD

**Issue by sayed4900** [I-TECH-UW/OpenELIS-Global-2#953]
@mozzy11 I am currently working on this issue.

**Comment by jwnasambu** [comment]
@sayed4900 Kindly, are you still working on this issue?

**Comment by mozzy11** [comment]
@jwnasambu you can take on the issue

**Comment by Isabirye1515** [comment]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 114.861 sec <<< FAILURE! - in org.openelisglobal.cityStateZip.CityStateZipServiceTest
testDataBase(org.openelisglobal.cityStateZip.CityStateZipServiceTest)  Time elapsed: 0.781 sec  <<< ERROR!
org.dbunit.dataset.NoPrimaryKeyException: city_state_zip
        at org.dbunit.operation.UpdateOperation.getOperationData(UpdateOperation.java:72)
        at org.dbunit.operation.RefreshOperation$UpdateRowOperation.<init>(RefreshOperation.java:275)
        at org.dbunit.operation.RefreshOperation.createUpdateOperation(RefreshOperation.java:151)
        at org.dbunit.operation.RefreshOperation.execute(RefreshOperation.java:103)
        at org.openelisglobal.BaseWebContextSensitiveTest.executeDataSetWithStateManagement(BaseWebContextSensitiveTest.java:104)
        at org.openelisglobal.cityStateZip.CityStateZipServiceTest.setup(CityStateZipServiceTest.java:19)


Results :

Mr @mozzy11 ,seeems the database image lacks some configurations for this like the primary key
